stages:
  - build
  - deploy

build:
  stage: build
  image: eclipse-temurin:17
  variables:
    JAVA_FX_HOME: /usr/share/openjfx/lib
  before_script:
    - apt-get update
    - apt-get install -y ant openjfx unzip wget
  script:
    - ant

create-pages:
  stage: deploy
  image: node:lts
  script:
    - echo "Publishing page"
  pages:
    publish: documentation/docs
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH