project:
  type: website
  output-dir: docs
  
website:
  announcement:
    icon: info-circle
    content: "**Alert** - Page under development"
    dismissable: true
    position: below-navbar
  page-navigation: true
  title: "Super Sprader Parametrization" 
  navbar:
    search: true
    pinned: true
    left: 
      - text: "Description"
        href: src/index.qmd
      - text: "Parametization"
        href: src/parametrization.qmd
      - text: "Tutorial"
        href: src/tutorial.qmd
     
    tools:
    - icon: github
      href: https://github.com/EDIDPasteur
    
format:
  html:
    theme:
      light: minty
      dark: darkly
    self-contained: false
    toc: true
    toc-depth: 10
engine: knitr
editor: visual
