project:
  type: website
  output-dir: docs
  
website:
  page-navigation: true
  title: "Super Sprader Parametrization" 
  navbar:
    search: true
    pinned: true
    left: 
      - text: "Parametization"
        href: src/parametrization.qmd
      - text: "Tutorial"
        href: src/tutorial.qmd
     
    tools:
    - icon: github
      href: https://github.com/EDIDPasteur
    
format:
  html:
    theme:
      light: minty
    self-contained: false
    toc: true
    toc-depth: 10
engine: knitr
editor: visual
